export const Images = {
  logo: require('./images/LogoBg.png'),
  waves: require('./images/waves.png'),
  land1: require('./images/land1.png'),
  land2: require('./images/land2.png'),
  profileIcon: require('./images/profileIcon.png'),
  scanner: require('./images/scanner.png'),
  secure: require('./images/secure.png'),
  assets: require('./images/assets.png'),
  explore: require('./images/explore.png'),
  home: require('./images/home.png'),
  trade: require('./images/trade.png'),
  down:require('./images/down.png'),
  buy : require('./images/buy.png'),
  earn : require('./images/earn.png'),
  receive : require('./images/receive.png'),
  send : require('./images/send.png'),
  coinLogo : require('./images/coinLogo.png'),
  tradeLogo : require('./images/trade.png'),
  pros: require('./images/pros.png'),
  cross:require('./images/cross.png'),
  projects: require('./images/projectsMain.png'),
  projectLogo: require('./images/projectLogo.png'),
  list1: require('./images/list1.png'),
  list2: require('./images/list2.png'),
  list3: require('./images/list3.png'),
  list4: require('./images/list4.png'),
  list5: require('./images/list5.png'),
  list6: require('./images/list6.png'),
  backScreen: require('./images/backScreen.png'),
  comment: require('./images/comment.png'),
  iconCircle:require('./images/iconCircle.png'),
  prosImage: require('./images/prosImage.png'),
  crossOverlay: require('./images/closeOverlay.png'),
  primary: require('./images/primary.png'),
  primary1: require('./images/primary1.png'),
  primary2: require('./images/primary2.png'),
  social: require('./images/social.png'),
  nfts: require('./images/nfts.png'),
  trade1: require('./images/trade1.png'),
  trade2: require('./images/trade2.png'),
  earn1: require('./images/earn1.png'),
  earn2: require('./images/earn2.png'),
  bottomHead: require('./images/bottomHead.png'),
  up: require('./images/up.png'),
  checked: require('./images/checked.png'),
  back: require ('./images/back.png'),
  proBadge: require('./images/proBadge.png'),
  checked1: require('./images/checked1.png'),
  securityIcon:require('./images/securityIcon.png'),
identity:require('./images/identity.png'),
connections:require('./images/connections.png'),
referrals:require('./images/referrals.png'),
notifications:require('./images/notifications.png'),
contacts:require('./images/contacts.png'),
helpSupport:require('./images/helpSupport.png'),
forward:require('./images/forward.png'),
pro:require('./images/pro.png'),
secureIcon:require('./images/secureIcon.png'),
tick:require('./images/tick.png'),
downArrow:require('./images/downArrow.png'),
refresh:require('./images/refresh.png'),
whiteCross:require('./images/whiteCross.png'),
vaultIcon:require('./images/vaultIcon.png'),
solanaLogo: require('./images/solanaLogo.png'),
solanaBg: require('./images/solanaBg.png'),
backArrow: require('./images/backArrow.png'),
copy: require('./images/copy.png'),
pBottom: require('./images/profileBottomLogo.png'),
base: require('./images/baseLogo.png'),
qr1: require('./images/qr1.png'),
token1: require('./images/token1.png'),
token2: require('./images/token2.png'),
token3: require('./images/token3.png'),
token4: require('./images/token4.png'),
token5: require('./images/token5.png'),
token6: require('./images/token6.png'),
token7: require('./images/token7.png'),
token8: require('./images/token8.png'),
downArroww: require('./images/downArroww.png'),
searchIcon: require('./images/searchIcon.png'),
overlayBackground: require('./images/overlayBackground.png'),
tradeBottom: require('./images/tradeBottom.png'),
titanium:require('./images/titanium.png'),
insured:require('./images/insured.png'),
sent:require('./images/sent.png'),
received:require('./images/received.png'),
rocket:require('./images/rocket.png'),
cashOut:require('./images/cashOut.png'),
return:require('./images/return.png'),
solana:require('./images/solana.png'),
bothSolanaBase:require('./images/bothSolanaBase.png'),
ethereum:require('./images/ethereum.png'),
bitCoin:require('./images/bitCoin.png'),
sol:require('./images/sol.png'),
usd:require('./images/usd.png'),
dai:require('./images/dai.png'),
aero:require('./images/aero.png'),
bret:require('./images/bret.png'),
lido:require('./images/lido.png'),
search:require('./images/search.png'),
coinBase:require('./images/coinBase.png'),
nft1:require('./images/nft1.png'),
nft2:require('./images/nft2.png'),
nft3:require('./images/nft3.png'),
nft4:require('./images/nft4.png'),
nft5:require('./images/nft5.png'),
nft6:require('./images/nft6.png'),
nft7:require('./images/nft7.png'),
nft8:require('./images/nft8.png'),
failed:require('./images/failed.png'),
pending:require('./images/pending.png'),
cancel:require('./images/cancel.png'),
qr:require('./images/qr.png'),
sync:require('./images/sync.png'),
swap:require('./images/swap.png'),
warning:require('./images/warning.png'),
sellerLogo:require('./images/sellerLogo.png'),
buyerLogo:require('./images/buyerLogo.png'),
baseCardLogo: require('./images/baseCardLogo.png'),
baseBg: require('./images/baseCardBg.png'),
hamBurger:require('./images/hamBurger.png'),
hamBurgerBg:require('./images/hamBurger.png'),
slb: require('./images/slb.png'),
profileHeadLogo: require('./images/profileHeadLogo.png'),
questionMark:require('./images/questionMark.png'),
cash:require('./images/cash.png'),
redDown:require('./images/redDown.png'),
greenUp:require('./images/greenUp.png'),
secure1: require('./images/secure1.png'),
swipeArrow: require('./images/swipeArrow.png'),
check:require('./images/check.png'),
ape:require('./images/ape.png'),
polygon:require('./images/polygon.png'),
usdc:require('./images/usdc.png'),
dogeCoin:require('./images/dogeCoin.png'),
chainLink:require('./images/chainLink.png'),
shiba:require('./images/shiba.png'),
jupiter:require('./images/jupiter.png'),
tether:require('./images/tether.png'),
bonk:require('./images/bonk.png'),
render:require('./images/render.png'),
raydium:require('./images/raydium.png'),
arrowForward:require('./images/arrowForward.png'),
backYellow:require('./images/backYellow.png'),
baseSmall:require('./images/baseSmall.png'),
launchArrowUp: require('./images/launchArrowUp.png'),
headImage: require('./images/headImg.png'),
proBadge1: require('./images/proBadge1.png'),
greenArrowUp: require('./images/greenArrowUp.png'),
backButton: require('./images/backButton.png'),
baseLogo: require('./images/baseLogo.png'),
tickAuth: require('./images/tickAuth.png'),
introducingArrow: require('./images/introducingArrow.png'),
tradeTick: require('./images/tradeTick.png'),
baseMini: require('./images/baseMini.png'),
user: require('./images/user.png')
}
